name = "notion-survey-ai"
compatibility_date = "2024-01-01"
pages_build_output_dir = "./dist"

# These environment variables will be set in Cloudflare dashboard
# [vars]
# NOTION_API_KEY = "secret_xxx"  # Set in dashboard
# NOTION_PARENT_PAGE_ID = "xxx"  # Set in dashboard
# NOTION_VERSION = "2022-06-28"